# Generated by Django 4.2.7 on 2024-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EventDisplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("details", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("event_venue_id", models.IntegerField()),
                ("attendee_count", models.IntegerField()),
            ],
        ),
    ]
